"""empty message

Revision ID: 2048a6ac11fd
Revises: 
Create Date: 2024-12-04 22:41:02.514585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2048a6ac11fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prediction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_name', sa.String(length=64), nullable=True),
    sa.Column('total_population', sa.Integer(), nullable=True),
    sa.Column('gdp_per_capita', sa.Integer(), nullable=True),
    sa.Column('percentage_male', sa.Integer(), nullable=True),
    sa.Column('percentage_urban', sa.Integer(), nullable=True),
    sa.Column('human_development_index', sa.Float(), nullable=True),
    sa.Column('temperature_increase', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    op.drop_table('prediction')
    # ### end Alembic commands ###
